version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: ai_translation_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
      - ./media:/backend/media      
    env_file:
      - .env
    command: sh -c "crond && python manage.py migrate && tail -f /dev/null"

  frontend:
    build:
      context: .
    container_name: ai_translation_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/backend
      - ./media:/backend/media
    env_file:
      - .env
    command: >
      sh -c "streamlit run app.py"
    depends_on:
      - backend

volumes:
  db-data:
